### ISSUE TITLE
2022年10月02日QQ群公告

### ISSUE THREAD

**Issue by fangkuairen-steve** [slqwqxd/Edgeless-Ce#2]
#"Edgeless ce(Edgeless_alpha_4.2.0)alpha_1.0 "预备更新内容  
## bugfix

1. 修复上个版本任务栏多次重启的bug

##  new function

1. uwp支持
2. 自定义驱动
3. 适配vbox网络问题
4. 适配钉钉
5. 适配壁纸引擎

**Comment by fangkuairen-steve** [comment]
#"Edgeless ce(Edgeless_alpha_4.2.0)alpha_1.0_releasecode-anles(释放代号艾乐斯)"预备更新内容

**Comment by slqwqxd** [comment]
uwp容器没整好呢
