### ISSUE TITLE
 规划(**大饼**)

### ISSUE THREAD

**Issue by fangkuairen-steve** [slqwqxd/Edgeless-Ce#4]
## Fly nt setup
具体来说有以下功能
主题(可能不会出)
热更新自己
安装预配(类似封装汐统的功能,但只要原版镜像就能自定义汐统)
不会加广告和sb VIP
汐统下载用迅雷+aria2
beta丢[屑的仓库](https://slqwqsoft-my.sharepoint.com/:f:/g/personal/shizuku_slqwqsoft_onmicrosoft_com/EpHIxotAh9ZHh0nmF13uNi0BrRiI5cmq70UI8ePBOCphtw?e=0OjGJg)

**Comment by fangkuairen-steve** [comment]
大饼一块

**Comment by slqwqxd** [comment]
别在这里发电
